PayPushNotificationsService: 
    Db:
        LogsConnString:
            settings-key: LykkePayLogsConnString
            types: [ AzureTableStorage, Tag ]
        DataConnString: 
            settings-key: LykkePayDataConnString
            types: [ AzureTableStorage, Tag ]
        EmployeeNotificationIdsTableName: EmployeeNotificationIds
        MerchantNotificationIdsTableName: MerchantNotificationIds
        NotificationsTableName: Notifications
    Rabbit:
        ConnectionString: 
            settings-key: RabbitPay
            types: [ RabbitMq, Tag ]
        ExchangeName: 
            settings-key: PayPushNotificationsService-ExchangeName
            types: [ Tag ]
        QueueName: 
            settings-key: PayPushNotificationsService-QueueName
            types: [ Tag ]
    HubName:
        settings-key: PayPushNotificationsService-HubName
        types: [ Tag ]
    HubConnectionString: 
        settings-key: PayPushNotificationsService-HubConnectionString
        types: [ Tag ]
      
MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl
    types: [ Tag ]

SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types: [ AzureTableStorage ]
    QueueName:
      settings-key: SlackQueueName
      types: [ AzureTableStorage ]